[package]
name = "klattice"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

[dependencies]
klattice-api = { path = "pkg/api" }

[workspace]
members = [
    "pkg/api",
    "pkg/hub",
    "pkg/plan",
]